package ch14PatternMatchingAndCaseClasses.s15SimulatingEnumerations

sealed abstract class TrafficLightColor
case object Red extends TrafficLightColor
case object Yellow extends TrafficLightColor
case object Green extends TrafficLightColor

